import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const instrumentSansVariable = localFont({
  src: [
    {
      path: './fonts/InstrumentSansVariable.ttf',
      style: 'normal'
    },
    {
      path: './fonts/InstrumentSansItalicVariable.ttf',
      style: 'italic'
    }
  ],
  variable: "--font-instrument-sans",
  fallback: ['sans-serif'],
})

const instrumentSansStatic = localFont({
  src: [
    {
      path: './fonts/static/InstrumentSans-Regular.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: './fonts/static/InstrumentSans-SemiBold.ttf',
      weight: '600',
      style: 'normal'
    },
    {
      path: './fonts/static/InstrumentSans-Bold.ttf',
      weight: '700',
      style: 'normal'
    }
  ],
  variable: "--font-instrument-sans-static",
  fallback: ['sans-serif'],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSansVariable.variable} ${instrumentSansStatic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
